#!/usr/bin/perl
while (<STDIN>) {
    #next if (/^\d{4}-\d{2}-\d{2}/); 
    print if (/^\d{4}-\d{2}-\d{2}\s(\d{2}:){2}(\d{2})\s[A-Z]{3}:\s[A-Z0-9]{4,6}-\d{2}>(APRS|APZUME),WIDE2-1,qA(R|S),[A-Z]{1,2}\d[A-Z]{1,3}(-\d)?:\/\d{6}h\d{4}\.\d{2}(N|S)\/\d{5}\.\d{2}(W|E)O\d{3}\/\d{3}\/A=\d{6}/);
}
