#!/usr/bin/perl
# Author: Nicholas LaJoie 
# ECE 331 – Homework 4, Problem 1
# Date: February 16, 2017
# Description: Perl Script for validating APRS data passed via stdin, prints to console if it matches

while (<STDIN>) {
    print if /^(\d{4}-\d{2}-\d{2})\s((\d{2}:){2}(\d{2}))\s[A-Z]{3}:\s[A-Z0-9]{4,6}-?(\d+)?>(APRS|APZUME),([A-Z0-9]{4,6},)?[A-Z0-9\*-]+,qA(R|S),[A-Z0-9]{4,6}-?(\d+)?:\/(\d{6})h(\d{4}\.\d{2}(N|S))\/(\d{5}\.\d{2}(W|E))O\d{3}\/\d{3}\/A=(\d{6})(\/Ti=-?\d+\/Te=-?\d+\/V=-?\d+)?(![a-zA-Z0-9]{3}!\/a=\d+\.\d+\/R=\d+)?([\w\s]+)?$/;
}
