#!/usr/bin/perl
# Script parses all lines in /etc/passwd file, creates hash that associates usernames with shells for all users
# Once parsed, prints each username and shell, one per line

open(IN, "/etc/passwd") or die "Cannot open \"/etc/passwd\" file.\n"; # Open file for parsing

my %pairs; # Hash to store username-shell pairs

while (<IN>) {
	chomp;
	my @L = split ':';
    $pairs{$L[0]} = $L[6]; # Store pair in the hash
}

for my $x (keys %pairs) {
    print "$x $pairs{$x}\n"; # Print each pair of username and shell
}
